// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABb1xLxIjAEqiH3AyKhVwTIWuLcB0rtB4',
    appId: '1:295991476735:web:5af4c341ba192eaaaf67ca',
    messagingSenderId: '295991476735',
    projectId: 'testingspoty',
    authDomain: 'testingspoty.firebaseapp.com',
    storageBucket: 'testingspoty.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgnQeBWJtDzqXOW1XlCH93fCYFoJif-0s',
    appId: '1:295991476735:android:f159e18a06f7d271af67ca',
    messagingSenderId: '295991476735',
    projectId: 'testingspoty',
    storageBucket: 'testingspoty.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi8pJlyKhtSGIlYh6d7C-f0ltn-v3J_Oc',
    appId: '1:295991476735:ios:3de684cfa249ed5baf67ca',
    messagingSenderId: '295991476735',
    projectId: 'testingspoty',
    storageBucket: 'testingspoty.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi8pJlyKhtSGIlYh6d7C-f0ltn-v3J_Oc',
    appId: '1:295991476735:ios:3de684cfa249ed5baf67ca',
    messagingSenderId: '295991476735',
    projectId: 'testingspoty',
    storageBucket: 'testingspoty.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABb1xLxIjAEqiH3AyKhVwTIWuLcB0rtB4',
    appId: '1:295991476735:web:c8ce45659978d9e1af67ca',
    messagingSenderId: '295991476735',
    projectId: 'testingspoty',
    authDomain: 'testingspoty.firebaseapp.com',
    storageBucket: 'testingspoty.firebasestorage.app',
  );
}
